# Generated by Django 4.0.5 on 2022-06-24 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CotizaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta fecha particular', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Disponibilidad de la fecha', max_length=1)),
                ('cotiza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cotizainstance')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
